--- 
name: rhodes-sugar-sample
bbver: 4.6
sdk: /Users/lars/Dev/code/rhomobile/rhodes
applog: rholog.txt
version: 0.2.0
vendor: rhomobile
iphone: 
  sdk: iphonesimulator3.0
  codesignidentity: ""
  entitlements: ""
  configuration: Debug
