sdk: "c:/src/rhodes"
sdkversion: 1.5.0
name: sugar_app
version: 1.1
vendor: rhomobile
bbver: 4.7
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator3.0
  provisionprofile:
  codesignidentity:
  entitlements:
extensions: ["extension-name-here", "second-extension-name"]
